[features]
seeds = false
skip-lint = false

[programs.devnet]
todo_list_app = "4nbBNaMniUJR9rG61AkL6af8M6e9g2Wgfh5FpMJ3L7dN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
